import { expect, test } from "bun:test";

const html = await Bun.file(new URL("../cloudflare/relay/client.html", import.meta.url)).text();
const script = html.match(/<script[^>]*>([\s\S]*)<\/script>/)?.[1] ?? "";

test("relay client script parses and exposes the complete multi-session control path", () => {
  expect(() => new Function(script)).not.toThrow();
  expect(script).toContain('"/sessions?session="');
  expect(script).toContain("hostId: host");
  expect(script).toContain("const pending = new Map()");
  expect(script).toContain("nekoRelayHistory");
  expect(script).toContain("drafts[currentHost()]");
  expect(script).toContain('localStorage.removeItem("nekoRelayHistory")');
  expect(script).toContain("rr.status === 401");
});

test("relay client keeps terminal semantics and accessible control names", () => {
  expect(html).toContain('role="log"');
  expect(html).toContain('<script nonce="__CSP_NONCE__">');
  expect(html).toContain('<style nonce="__CSP_NONCE__">');
  expect(html).toContain('aria-label="message Neko"');
  expect(html).toContain('aria-label="switch Neko session"');
  expect(script).toContain('t.className = "turn user"');
  expect(script).toContain('t.className = "turn neko"');
  expect(html).toContain('class="pr">&gt;</span>');
  expect(html).toContain('id="hversion">v0.9.0</small>');
  expect(html).toContain('Try: "explain src/agent.ts"   or   /help');
  expect(html).toContain("width: 100%; max-width: none; height: 100dvh");
  expect(html).toContain("interactive-widget=resizes-content");
  expect(html).not.toContain("maximum-scale=1");
  expect(html).toContain("min-width: 44px; height: 44px");
  expect(html).toContain("min-height: 44px; max-height: min(112px, 24dvh)");
  expect(html).toContain("max-height: min(54dvh, 360px)");
  expect(script).toContain('compact ? "Message Neko..."');
  expect(script).toContain('compact ? " · working · tap stop"');
  expect(script).toContain('e.key === "Escape"');
  expect(script).toContain('e.key === "Tab" && e.shiftKey');
  expect(script).toContain('"\\u0000neko:cycle-mode"');
  expect(script).toContain("log.scrollHeight - log.clientHeight - log.scrollTop");
  expect(script).toContain('location.pathname.match(/^\\/(?:session|hub)');
  expect(script).toContain("nekoRelayPairings");
  expect(script).toContain("const legacyMatches = localStorage.nekoSession === session.value");
  expect(script).toContain('"/client-ws?session="');
  expect(script).toContain('frame.t === "mirror_reset"');
  expect(script).toContain('event.type === "snapshot"');
  expect(script).toContain("connectMirror(true)");
  expect(script).toContain("Math.min(1_000 * 2 ** mirrorFailures++, 25_000)");
  expect(script).toContain('frame.t === "presence"');
  expect(script).toContain('headerBits.push("browser attached")');
  expect(script).toContain("hostWorking(host)");
  expect(script).toContain("isRelaySetupLine(line)");
  expect(html).toContain(".composer:focus-within");
  expect(html).toContain(".foot { position: relative; z-index: 20");
  expect(html).toContain("#log { position: relative; z-index: 0");
  expect(html).toContain('id="slashmenu" role="listbox"');
  expect(html).toContain('aria-autocomplete="list"');
  expect(html).toContain('role="combobox"');
  expect(script).toContain('e.key === "ArrowDown"');
  expect(script).toContain("e.isComposing");
  expect(script).toContain("acceptSlash(true)");
  expect(script).toContain("requestAnimationFrame(focusComposer)");
  expect(script).toContain("selectedHost()?.meta?.commands");
  expect(html).toContain('id="liveui" role="region"');
  expect(script).toContain('base() + "/control"');
  expect(script).toContain("sendApproval(decision, approval.id)");
  expect(script).toContain('sendOverlay("select"');
  expect(script).toContain("overlay.description");
  expect(script).toContain('button.setAttribute("role", "option")');
  expect(script).toContain("mirrorSeqByHost[host]");
  expect(script).toContain("moveHistory(-1)");
  expect(script).toContain("navigator.clipboard.writeText(text)");
  expect(script).toContain('box.dataset.key = "pairing-mismatch"');
  expect(script).toContain('title.textContent = "Pairing key changed"');
  expect(script).toContain('$("send").disabled = approval || overlay || kidMismatch');
  expect(script).not.toContain("if (kidMismatch) { const nk = nekoTurn()");
});
