/**
 * `neko setup web` — one command to stand up the SOTA web stack and wire it into config:
 *   - SearXNG (Docker, JSON API enabled) -> strong metasearch (far better than DuckDuckGo);
 *   - browser MCP (@playwright/mcp, headed real-Chrome) -> JS / bot-walled pages.
 * Idempotent, key-safe (never touches api_key), and degrades gracefully (clear [skip] messages).
 * Extensible: `setup <component>` — add a component = add a branch, no rewrite.
 */
import { spawnSync } from "node:child_process";
import { mkdirSync, writeFileSync } from "node:fs";
import { join } from "node:path";

import { homeDir } from "../shared/home.ts";
import { addMcpServer, patchUserConfig } from "./project.ts";

const SEARXNG_PORT = 8888;
const SEARXNG_BASE = `http://localhost:${SEARXNG_PORT}`;
// JSON API is OFF by default (and on public instances) — Neko's backend needs it on.
const SETTINGS_YML = `# Neko SearXNG — generated by 'neko setup web'. JSON API on so Neko's web_search can read it.
use_default_settings: true
server:
  secret_key: "neko-local-searxng-secret"
  limiter: false
search:
  formats:
    - html
    - json
`;

const sleep = (ms: number) => new Promise((r) => setTimeout(r, ms));
function ok(cmd: string, args: string[]): boolean {
  try { return spawnSync(cmd, args, { encoding: "utf8", timeout: 12000 }).status === 0; } catch { return false; }
}

/** Wire the browser MCP (headed real-Chrome — least bot-detectable). Needs bunx or npx. */
function setupBrowser(log: (m: string) => void): boolean {
  const runner = ok("bunx", ["--version"]) ? "bunx" : ok("npx", ["--version"]) ? "npx" : "";
  if (!runner) { log("  [skip] browser MCP — need bunx or npx (install Bun or Node)."); return false; }
  const base = ["@playwright/mcp@latest", "--isolated", "--browser", "chrome"];
  addMcpServer("browser", { command: runner, args: runner === "npx" ? ["-y", ...base] : base });
  log(`  [ok]   browser MCP -> ${runner} @playwright/mcp (headed Chrome). If Chrome/Chromium missing: '${runner} playwright install chromium'.`);
  return true;
}

/** Stand up SearXNG in Docker with the JSON API on, verify it, and wire searxng_url into config. */
async function setupSearxng(log: (m: string) => void): Promise<boolean> {
  if (!ok("docker", ["ps"])) {
    log("  [skip] SearXNG — Docker isn't running. Start Docker Desktop and re-run, or set TAVILY_API_KEY (free) for SOTA search.");
    return false;
  }
  const dir = join(homeDir(), "neko-searxng");
  mkdirSync(dir, { recursive: true });
  writeFileSync(join(dir, "settings.yml"), SETTINGS_YML, "utf-8");
  spawnSync("docker", ["rm", "-f", "neko-searxng"], { encoding: "utf8", timeout: 30000 }); // idempotent
  // No --restart policy on purpose: Neko manages the lifecycle (Ollama-style) - web_search auto-starts
  // the container on demand and auto-stops it after `searxng_keepalive` idle minutes, so it costs zero
  // RAM between uses instead of idling forever.
  const run = spawnSync("docker", [
    "run", "-d", "--name", "neko-searxng",
    "-p", `${SEARXNG_PORT}:8080`, "-v", `${dir}:/etc/searxng`, "searxng/searxng:latest",
  ], { encoding: "utf8", timeout: 240000 });
  if (run.status !== 0) { log(`  [fail] SearXNG container — ${(run.stderr || run.stdout || "").trim().slice(0, 200)}`); return false; }
  log("  ...   SearXNG container started; waiting for the JSON API...");
  for (let i = 0; i < 14; i++) {
    await sleep(2500);
    try {
      const res = await fetch(`${SEARXNG_BASE}/search?format=json&q=test`, { signal: AbortSignal.timeout(8000) });
      if (res.ok) {
        const data: any = await res.json();
        if (Array.isArray(data.results)) {
          patchUserConfig({ searxng_url: SEARXNG_BASE, search_backend: "searxng" });
          log(`  [ok]   SearXNG -> ${SEARXNG_BASE} (JSON API, ${data.results.length} results), config wired.`);
          log("  [ok]   lifecycle is managed: web_search wakes the container on demand and stops it after 15 idle minutes (searxng_keepalive; 0 = keep running).");
          return true;
        }
      }
    } catch { /* still booting */ }
  }
  log("  [warn] SearXNG container is up but the JSON API didn't respond in time — check `docker logs neko-searxng`, then `neko setup searxng` again.");
  return false;
}

/** Verify a Tavily key against the live API, then wire it into user config (`tavily_api_key`,
 * gitignored + redacted when printed). The no-Docker rung of the search ladder: hosted, free tier,
 * one key. The key itself is NEVER echoed. */
async function setupTavily(keyArg: string, log: (m: string) => void): Promise<boolean> {
  const key = (keyArg || process.env.TAVILY_API_KEY || "").trim();
  if (!key) {
    log("  [skip] Tavily — no key. Get a free one at https://app.tavily.com, then either:");
    log("           neko setup tavily <key>      (note: the key lands in your shell history)");
    log("           or set TAVILY_API_KEY and re-run `neko setup tavily`.");
    return false;
  }
  log("  ...   verifying the key against api.tavily.com...");
  try {
    const res = await fetch("https://api.tavily.com/search", {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ api_key: key, query: "neko setup probe", max_results: 1 }),
      signal: AbortSignal.timeout(20000),
    });
    if (!res.ok) { log(`  [fail] Tavily rejected the key (HTTP ${res.status}) — nothing written. Check it at https://app.tavily.com.`); return false; }
  } catch (e) {
    log(`  [fail] could not reach api.tavily.com (${(e as Error).message}) — nothing written; re-run when online.`);
    return false;
  }
  patchUserConfig({ tavily_api_key: key });
  log("  [ok]   Tavily key verified + wired into ~/.neko-core/config.json (redacted in `neko config`).");
  log("  [ok]   ladder: SearXNG (if configured) > Tavily > DuckDuckGo — Tavily also catches SearXNG failures.");
  return true;
}

/** `neko setup [web|searxng|browser|tavily]`. Returns a process exit code. */
export async function setupWeb(component: string, log: (m: string) => void, extra = ""): Promise<number> {
  const which = (component || "web").toLowerCase();
  if (!["web", "searxng", "browser", "tavily"].includes(which)) {
    log(`Unknown setup target '${which}'. Use: neko setup [web|searxng|browser|tavily]`);
    return 2;
  }
  log(`Setting up the web stack (${which})...`);
  let allOk = true;
  if (which === "web" || which === "browser") allOk = setupBrowser(log) && allOk;
  if (which === "web" || which === "searxng") allOk = (await setupSearxng(log)) && allOk;
  if (which === "tavily") allOk = (await setupTavily(extra, log)) && allOk;
  log(allOk
    ? "\nDone. Verify: `neko doctor` (web_search) and `neko mcp` (browser). See docs/process/WEB.md."
    : `\nFinished with [skip]/[warn]/[fail] above — the rest is wired. Fix those and re-run \`neko setup ${which}\`.`);
  return allOk ? 0 : 1;
}
