/**
 * One-off: bake assets/neko-core-banner.png into src/ui/logo.tsx as terminal half-block art.
 * Run: bun scripts/gen-logo.ts   (dev-only; the output has no runtime dependency).
 */
import { readFileSync, writeFileSync } from "node:fs";
import { PNG } from "pngjs";

const TARGET_WIDTH = 78; // output columns
const png = PNG.sync.read(readFileSync("assets/neko-core-banner.png"));
const { width, height, data } = png;

const on = (x: number, y: number): boolean => {
  if (x < 0 || y < 0 || x >= width || y >= height) return false;
  const i = (y * width + x) * 4;
  const lum = 0.299 * data[i] + 0.587 * data[i + 1] + 0.114 * data[i + 2];
  return data[i + 3] > 128 && lum < 128; // opaque + dark = glyph
};

const scale = width / TARGET_WIDTH;
let th = Math.round(height / scale);
if (th % 2 === 1) th += 1; // even rows for half-block pairing

// Coverage threshold over the source block (preserves letter gaps, unlike any-on).
const cell = (tx: number, ty: number): boolean => {
  const x0 = Math.floor(tx * scale);
  const x1 = Math.max(x0 + 1, Math.floor((tx + 1) * scale));
  const y0 = Math.floor(ty * (height / th));
  const y1 = Math.max(y0 + 1, Math.floor((ty + 1) * (height / th)));
  let dark = 0;
  let total = 0;
  for (let y = y0; y < y1; y++) for (let x = x0; x < x1; x++) {
    total++;
    if (on(x, y)) dark++;
  }
  return total > 0 && dark / total >= 0.4;
};

let rows: string[] = [];
for (let ry = 0; ry < th; ry += 2) {
  let line = "";
  for (let tx = 0; tx < TARGET_WIDTH; tx++) {
    const top = cell(tx, ry);
    const bot = cell(tx, ry + 1);
    line += top && bot ? "█" : top ? "▀" : bot ? "▄" : " ";
  }
  rows.push(line.replace(/\s+$/, "")); // trim trailing spaces
}
while (rows.length && rows[0].trim() === "") rows.shift(); // drop empty top rows
while (rows.length && rows[rows.length - 1].trim() === "") rows.pop(); // and bottom

const out =
  `// AUTO-GENERATED by scripts/gen-logo.ts from assets/neko-core-banner.png. Do not edit.\n` +
  `import { Box, Text } from "ink";\n\n` +
  `const ROWS = ${JSON.stringify(rows, null, 0)};\n\n` +
  `export function Logo() {\n` +
  `  return (\n` +
  `    <Box flexDirection="column">\n` +
  `      {ROWS.map((r, i) => (\n` +
  `        <Text key={i} color="magenta">{r || " "}</Text>\n` +
  `      ))}\n` +
  `    </Box>\n` +
  `  );\n` +
  `}\n`;

writeFileSync("src/ui/logo.tsx", out, "utf-8");
console.log(`wrote src/ui/logo.tsx (${rows.length} rows x ${TARGET_WIDTH} cols)`);
